# docker-compose.yml
version: '3.3'

services:
  # Django application
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: django-docker-app
    volumes:
      - ./:/app/
      - ./appfiles:/appfile
  # Nginx as proxy server.
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: django-docker-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./appfiles/static/:/appfiles/static/
      - ./appfiles/media/:/appfiles/media/
    restart: unless-stopped
    depends_on:
      - app

