version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8080:3306
    volumes:
      - ./script/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./mysql-data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: mysql



