version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8082:3306
    volumes:
      - ./script/script_test_db.sql:/docker-entrypoint-initdb.d/script_test_db.sql
      - ./mysql-data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: mysql



