# Generated by Django 4.0.4 on 2022-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='user',
        ),
    ]
