# Generated by Django 4.0.4 on 2022-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_computers_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='host_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
