# Generated by Django 4.0.4 on 2022-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bookings_end_alter_bookings_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='end',
            field=models.DateTimeField(blank=True, db_column='end_time', null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start',
            field=models.DateTimeField(blank=True, db_column='start_time', null=True),
        ),
    ]
