# Generated by Django 4.0.4 on 2022-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookings_end_alter_bookings_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'global_variables',
                'managed': True,
            },
        ),
    ]
